### ISSUE TITLE
order in device_Id_array

### ISSUE THREAD

**Issue by pol22pol** [BlazejosP/huawei-sun2000-API-CLI#11]
In fusionsolarapp.sh you are using static relation to second position in array device_Id_array. You should check type of device because fusion can send device in other order. For example in my installation I received

	Device 1: 7534929584736
	Smart String Inverter	Inverter Type: SUN2000-5KTL-M0
	Device Name: HV20500....
	Device SN: HV20500....
	Software version: V100R001C00SPC122

	Device 2: 45711197793123
	Dongle	Device Name: HV20500....
	Device SN: HV20500....
	Software version: V100R001C00SPC115

**Comment by BlazejosP** [comment]
Thanks for mentioning that. That was for now just the temporary solution just to proof that data can be pulled and show on the screen even if is just working in this specific configuration One Plant -> 2 devices [first inverter second Dongle] I have exactly the same configuration . I d'like to write interface which will show dynamically data on screen with use of TUI [LINUX terminal TUI](https://unix.stackexchange.com/questions/285777/how-do-i-create-a-terminal-based-gui) for user usage here you will be able chose from which Plant (Is possible more than one) and which device (as you mentioned can be in different order or can be more than one inverter or even more devices battery for example) you can present data on screen. Second issue is when TUI will be written will be just for user lookup sometimes. Real use of this  script will be automatically pull up data to InfluxDB/domoticz/MQTT. Actually my plan is to made in TUI configuration option where you chose what will  be scraped from which Plant->specific device  that will be saved in config file and then in background file will pull-up data which you chosen before with use of TUI.

**Comment by BlazejosP** [comment]
No that is my 

	Device 1: [12345679]
	Dongle	Device Name: bla bla
	Device SN: [bla bla]
	Software version: V100R001C00SPC111

	Device 2: [12345679]
	Smart String Inverter	Inverter Type: SUN2000-5KTL-M0
	Device Name: [bla bla] 
	Device SN: [bla bla]
	Software version: V100R001C00SPC120

So inverter in in second place as (Device 2) That is when I call inverter device inside different functions I use postion 1 in array we start from 0 in my case that is dongle in your case is reverse as you mentioned 

getDevRealKpi  ${device_Id_array[1]} ${device_TypeId_array[1]}			
			#getDevFiveMinutes ${device_Id_array[1]} ${device_TypeId_array[1]} $curent_time
			#getDevKpiDay ${device_Id_array[1]} ${device_TypeId_array[1]} $curent_time
			#getDevKpiMonth ${device_Id_array[1]} ${device_TypeId_array[1]} $curent_time
			#getDevKpiYear ${device_Id_array[1]} ${device_TypeId_array[1]} $curent_time
