### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by pol22pol** [BlazejosP/huawei-sun2000-API-CLI#2]
Can you share the database schema where the data is stored?

**Comment by BlazejosP** [comment]
Yes of course that isn't complicated database

**Comment by BlazejosP** [comment]
For example look in line 588 in bash file.
there is Power=alarms what means alarms descriptions are stored inside table "Power" and column "alarms" inside influxDB you can use my tables or create your own if you change this fields in curl commands. If that meaby usefully for you I can upload my already done grafana visualisation. In that case without changing names of tables/columns you can immediately see your data on graphs?

**Comment by pol22pol** [comment]
I think, Your grafana visualisation will be very useful. :-)
Did you try to use API from main FusionSolar site? They work similarly, but provide more informations.

**Comment by BlazejosP** [comment]
I uploaded my Grafana panel for you. This panel used my schematics of tables&columns in InfluxDB so you should have your data when you import him to Grafana, because tables are already created by curl commands from fusionsolarapp.sh if not existing. Now only in polish language but is enough for tests. And don't forget add Sun and Moon plugin in Grafana which is responsible for sun position graph.

**Comment by BlazejosP** [comment]
> Did you try to use API from main FusionSolar site? They work similarly, but provide more informations.
I already use their official API from FusionSolarAPP problem is that not everything what is inside their software is available through API. For example Temrature of Inverter or Actually inverted power.  Meaby they are scare that script like this will ask their servers too often.

**Comment by pol22pol** [comment]
Thx for your Grafana dashboard.
FusionSolar have OpenAPI with same base data. 
But when you enable singleKiosk then you have access to a simple API without authorization (you have to know id). For example https://eu5.fusionsolar.huawei.com/kiosk/getPowers give you access to data with 5 minutes interval.
Other API when you login to your account on https://eu5.fusionsolar.huawei.com/index.jsp.

Have you tried to use the second and third APIs?

**Comment by BlazejosP** [comment]
No I don't know about this simple API and access to *.jsp file So that means that are two additional sources of data from inverter especially missed ones. I only used An official one from Huawei documentation. I will investigate this and probably add [additional](url) data to *.sh file to improve software.

**Comment by BlazejosP** [comment]
> Thx for your Grafana dashboard.
> FusionSolar have OpenAPI with same base data.
> But when you enable singleKiosk then you have access to a simple API without authorization (you have to know id). For example https://eu5.fusionsolar.huawei.com/kiosk/getPowers give you access to data with 5 minutes interval.
> Other API when you login to your account on https://eu5.fusionsolar.huawei.com/index.jsp.
> 
> Have you tried to use the second and third APIs?

Just first version of new bash script which use "Kiosk mode" is already done it can insert data to influxDB and Domoticz in a few days I will also do an MQTT sending option. I also experimented  with taking data directly from fusionsoalarApp web interface there are quite interesting but i can't  grab them to bash script is necessary have cookies and some data from this file like session id  so I can't create them with use of bash

**Comment by pol22pol** [comment]
OK, I'll check kioskmode.
In kioskmode.sh on line 29 should be "true"

**Comment by BlazejosP** [comment]
> OK, I'll check kioskmode.
> In kioskmode.sh on line 29 should be "true"

My mistake already repaired
