### ISSUE TITLE
Offer to contribute

### ISSUE THREAD

**Issue by bhaezlr** [BlazejosP/huawei-sun2000-API-CLI#23]
Hello,

Your project got my interest.
I'm running Domoticz with mqtt and I 'm searching a way to get the data from huwei in my dashboard in Domoticz.
Especially the battery status.

Invert : SUN2000-4.6KTL-L1
Battery : HUAWEI-LUNA2000

If you like, maybe I can contribute to get these devices supported.

kind regards,
Bart

**Comment by BlazejosP** [comment]
Invitation to access repository is already seeded to you!
